# Generated by Django 2.2.7 on 2019-11-07 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0002_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='achievement',
            new_name='actual_achievement',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='amount',
            new_name='met_goal',
        ),
    ]
