# Generated by Django 2.2.7 on 2019-11-07 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0003_auto_20191107_0419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
