# Generated by Django 2.2.7 on 2019-11-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0005_auto_20191107_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
