# Generated by Django 2.2.7 on 2019-11-07 22:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0006_auto_20191107_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2019, 11, 7, 22, 15, 30, 451326)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='journal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2019, 11, 7, 22, 15, 51, 138274)),
            preserve_default=False,
        ),
    ]
