# Generated by Django 2.2.7 on 2019-11-08 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0007_auto_20191107_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='habit',
            field=models.CharField(max_length=255),
        ),
    ]
