# Generated by Django 2.2.7 on 2019-11-08 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0008_auto_20191108_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='goal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='habit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
