# Generated by Django 2.2.7 on 2019-11-08 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0010_auto_20191108_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='habit',
            field=models.CharField(blank=True, choices=[('workout', 'Workout'), ('eat veggies', 'Eat Veggies'), ('mango', 'Mangoes'), ('honeydew', 'Honeydews')], max_length=255, null=True),
        ),
    ]
