# Generated by Django 2.2.7 on 2019-11-08 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0014_journal_met_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='count',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='habits', to='habit_tracker.Journal'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='met_goal',
            field=models.BooleanField(default=False),
        ),
    ]
