# Generated by Django 2.2.7 on 2019-11-08 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0015_auto_20191108_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='count',
        ),
        migrations.AddField(
            model_name='journal',
            name='count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
