# Generated by Django 2.2.7 on 2019-11-08 21:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0017_habit_observers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='observers',
            field=models.ManyToManyField(blank=True, related_name='habits_observing', to=settings.AUTH_USER_MODEL),
        ),
    ]
