# Generated by Django 2.2.7 on 2019-11-10 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0018_auto_20191108_2146'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='habit',
            unique_together={('user', 'habit')},
        ),
    ]
